[package]
name = "xmrsplayer"
version = "0.1.3"
edition = "2021"
description = "XMrsPlayer is a portage of libxm in Rust language to play real music "
license = "MIT"
authors = ["Sebastien Bechet"]
documentation = "https://docs.rs/xmrsplayer"
repository = "https://github.com/sbechet/xmrsplayer"
readme = "README.md"

keywords = ["xm", "module", "mod", "s3m", "tracker"]
categories = ["multimedia::audio"]


[dependencies]
clap = { version = "^4.2", features = ["cargo", "derive"] }
bitflags = "2.0"
rodio = "0.17"
xmrs = "0.3"
console = "0.15.5"

[lib]
name = "xmrsplayer"
path = "src/lib.rs"

[[bin]]
name = "player"
path = "src/bin/player.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
